<a href="https://colab.research.google.com/github/evandrornunes/projeto-de-governan-a/blob/main/Unidade3%20Aula3%20Finalizado%20%20%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
df_selic = pd.read_json("https://api.bcb.gov.br/dados/serie/bcdata.sgs.11/dados?formato=json&dataInicial=25/09/2015")
print(df_selic.info())
print(df_selic)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    2509 non-null   object
 1   valor   2509 non-null   float64
dtypes: float64(1), object(1)
memory usage: 39.3+ KB
None
            data     valor
0     25/09/2015  0.052531
1     28/09/2015  0.052531
2     29/09/2015  0.052531
3     30/09/2015  0.052531
4     01/10/2015  0.052531
...          ...       ...
2504  18/09/2025  0.055131
2505  19/09/2025  0.055131
2506  22/09/2025  0.055131
2507  23/09/2025  0.055131
2508  24/09/2025  0.055131

[2509 rows x 2 columns]

In [10]:
df_selic.drop_duplicates(keep='last', inplace=True)

In [11]:
print(df_selic)

            data     valor
0     25/09/2015  0.052531
1     28/09/2015  0.052531
2     29/09/2015  0.052531
3     30/09/2015  0.052531
4     01/10/2015  0.052531
...          ...       ...
2504  18/09/2025  0.055131
2505  19/09/2025  0.055131
2506  22/09/2025  0.055131
2507  23/09/2025  0.055131
2508  24/09/2025  0.055131

[2509 rows x 2 columns]

In [23]:
from datetime import date
from datetime import datetime as dt

data_extracao = date.today()

df_selic['data_extracao'] = data_extracao
df_selic['responsavel'] = "Evandro_Nunes"

print(df_selic.info())

df_selic.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data           2509 non-null   object
 1   valor          2509 non-null   float64
 2   data_extracao  2509 non-null   object
 3   responsavel    2509 non-null   object
dtypes: float64(1), object(3)
memory usage: 78.5+ KB
None

         data     valor data_extracao    responsavel
0  25/09/2015  0.052531    2025-09-25  Evandro_Nunes
1  28/09/2015  0.052531    2025-09-25  Evandro_Nunes
2  29/09/2015  0.052531    2025-09-25  Evandro_Nunes
3  30/09/2015  0.052531    2025-09-25  Evandro_Nunes
4  01/10/2015  0.052531    2025-09-25  Evandro_Nunes
5  02/10/2015  0.052531    2025-09-25  Evandro_Nunes
6  05/10/2015  0.052531    2025-09-25  Evandro_Nunes
7  06/10/2015  0.052531    2025-09-25  Evandro_Nunes
8  07/10/2015  0.052531    2025-09-25  Evandro_Nunes
9  08/10/2015  0.052531    2025-09-25  Evandro_Nunes

In [24]:
df_selic.loc[4]

data                01/10/2015
valor                 0.052531
data_extracao       2025-09-25
responsavel      Evandro_Nunes
Name: 4, dtype: object

In [25]:
df_selic.loc[[3,20,70]]

          data     valor data_extracao    responsavel
3   30/09/2015  0.052531    2025-09-25  Evandro_Nunes
20  26/10/2015  0.052531    2025-09-25  Evandro_Nunes
70  07/01/2016  0.052531    2025-09-25  Evandro_Nunes

In [28]:
pesquisa = df_selic['valor'] < 0.01   # Função para filtrar valores que sao menos que 0.01 atraves de logica booleanas TRUE or False

print(type(pesquisa))

<class 'pandas.core.series.Series'>

In [29]:
print(pesquisa)

0       False
1       False
2       False
3       False
4       False
        ...
2504    False
2505    False
2506    False
2507    False
2508    False
Name: valor, Length: 2509, dtype: bool

In [3]:
import pandas as pd

# Criando um DataFrame com 5 linhas de dados
data = {

    'nome': ['Produto A', 'Produto B', 'Produto C', 'Produto A', 'Produto E'],

    'quantidade de itens comprados': [3, 1, 4, 3, 2],

    'tipo de item': ['Eletrônico', 'Vestuário', 'Alimento', 'Eletrônico', 'Alimento'],

    'receita total': [120, 80, 60, 120, 90]

}
df = pd.DataFrame(data)
print(df)

        nome  quantidade de itens comprados tipo de item  receita total
0  Produto A                              3   Eletrônico            120
1  Produto B                              1    Vestuário             80
2  Produto C                              4     Alimento             60
3  Produto A                              3   Eletrônico            120
4  Produto E                              2     Alimento             90

In [5]:
# Duplicando uma linha
df.drop_duplicates(keep='last', inplace=True)
print(df)

        nome  quantidade de itens comprados tipo de item  receita total
1  Produto B                              1    Vestuário             80
2  Produto C                              4     Alimento             60
3  Produto A                              3   Eletrônico            120
4  Produto E                              2     Alimento             90

Exercicio da aula

In [6]:
# Calculando a coluna 'preço do item'
df['preço do item'] = df['receita total'] / df['quantidade de itens comprados']

# Selecionando preço do item acima de 50 reais
itens_acima_de_50 = df[df['preço do item'] > 50]

print("Itens acima de 50 reais:")
print(itens_acima_de_50)

Itens acima de 50 reais:
        nome  quantidade de itens comprados tipo de item  receita total  \
1  Produto B                              1    Vestuário             80

   preço do item
1           80.0